### ISSUE TITLE
BUILD 5.3.4f1

### ISSUE THREAD

**Issue by A-312** [Silly-Machines/Algoquid#13]
Le projet n'a pas été ouvert pendant un bon mois, et dans une version ancienne (**5.1.1f1**), Unity3D est passé en **5.3.4f1** avec un petit changement avec la fonction `Color.TryParseHexString` qui n'est plus disponible depuis la 5.2.

[[FIXED] Unity 5.2.03f New Bug or Function Disapeared!?](http://forum.unity3d.com/threads/fixed-unity-5-2-03f-new-bug-or-function-disapeared.353908/)

**Comment by A-312** [comment]
@ThuleMalta Je n'ose pas passer la PR, je ne voudrais pas te forcer à MaJ Unity, si tu es en vacances, avec une connexion faible.
Normalement le code que j'ai remplacé devrait fonctionner en **5.1.1f1** aussi.

```
var color = new Color(0.89F, 0.89F, 0.89F, 1);
```

D'ailleurs Unity3D se donne à cœur joie de modifier des fichiers `.asset`, alors qu'on fait que l'ouvrir/fermer sans rien toucher. Je ne sais pas trop comment on doit interpréter ça.

Apparemment, il faudrait rajouter un contrôle de version avec les fichiers `.meta`, pour ne pas avoir ce genre de soucis. (Je suis entrain de chercher sur cette piste).

**Comment by A-312** [comment]
La solution est ici : [How to use Git for Unity source control ?](http://stackoverflow.com/questions/18225126/how-to-use-git-for-unity-source-control)

> ## Unity3D Settings
> 
> For versions of Unity 3D v4.3 and up:
> 1. (Skip this step in v4.5 and up) Enable `External` option in `Unity → Preferences → Packages → Repository`. 
> 2. Switch to `Visible Meta Files` in `Edit → Project Settings → Editor → Version Control Mode`.
> 3. Switch to `Force Text` in `Edit → Project Settings → Editor → Asset Serialization Mode`.
> 4. Save the scene and project from `File` menu.

**Comment by ghost** [comment]
C'est noté. En effet ma connexion ne me permet pas pour le moment de
télécharger Unity 5.3.
