### ISSUE TITLE
Tag/label github

### ISSUE THREAD

**Issue by A-312** [Silly-Machines/Algoquid#27]
@viki53 Il faudrait refaire les labels/tag de git pour mieux classer les issues.

Certains sont inutiles ou manquants, ou correspondent à deux catégories...

Je propose _16 labels_ : 
- Menu / Jeu / Éditeur / Unity3D
- Modélisation (3D) / Graphisme (2D) / Code / Animation
- Régression / Évolution / Bloquant / Facile
- Fondamental (GL) / Question / Discussion / Bug

(GL pour Guideline -> équivalent des zep / Unity3D => Gérer le projet Unity3D (= Unity3Dsettings) ainsi que le classement dans les dossiers).

**Comment by viki53** [comment]
T'as pas les droits sur les labels ? C'est bizarre, t'es admin normalement sur le repo…

Sinon, pour le détail, ça a été discuté/validé avec les autres ?

**Comment by ghost** [comment]
Personnellement je suis d'accord.

**Comment by A-312** [comment]
Comme je l'ai dis sur gitter, je pensais ne pas avoir l'accès et que ça dépendais du groupe Silly-Machines.

J'ai découvert l'interface ~~caché~~ : https://github.com/Silly-Machines/Algoquid/labels

**Comment by viki53** [comment]
Parfait 👍
