### ISSUE TITLE
Trello introuvable

### ISSUE THREAD

**Issue by ShiiFu** [Silly-Machines/Algoquid#29]
Le lien pour voir les tâches sur trello est cassé. 
[Trello](https://trello.com/b/VF72jZdk/algoquid) nous indique que le tableau est introuvable. 

Celui-ci est privé ou n'existe pas/plus ?

**Comment by A-312** [comment]
Il semble être disponible, il faut juste avoir l'accès.

**Comment by ShiiFu** [comment]
Pourquoi ne pas le mettre visible par tous et modifiable par certaines personnes ?

**Comment by A-312** [comment]
Ping @viki53. Je te laisse répondre, je ne suis pas apte à fournir des réponses. ;)

**Comment by viki53** [comment]
Parce que je n'en voyais pas l'intérêt à première vue. 

Mais ça peut effectivement être un moyen de montrer l'avancement du projet. Je viens donc de le passer en public. :)
