### ISSUE TITLE
Design du menu

### ISSUE THREAD

**Issue by ghost** [Silly-Machines/Algoquid#4]
Les graphistes 2D et ceux ayant de l'expérience avec le système d'UI Unity3D sont les bienvenus. Le design actuel du menu est un peu (pour ne pas dire très) moche...

![rmfuztg](https://cloud.githubusercontent.com/assets/5496460/11913795/99d07a7c-a670-11e5-852d-503a9a6d5ac7.png)

**Comment by viki53** [comment]
Je pense que ça peut attendre, il vaut mieux voir l'univers du jeu à proprement parler avant de choisir le style des menus, histoire de ne pas se retrouver avec des mélanges bizarres

**Comment by ghost** [comment]
Pour information, un nouveau menu a été ajouté par la PR #7 il y a quelques mois. Je ferme l'issue en attendant d'avoir un graphiste 2D.
